replace `1' = "Afghanistan" if `1' =="AF"
replace `1' = "Albania" if `1' =="AL"
replace `1' = "Algeria" if `1' =="DZ"
replace `1' = "American Samoa" if `1' =="AS"
replace `1' = "Andorra" if `1' =="AD"
replace `1' = "Angola" if `1' =="AO"
replace `1' = "Anguilla" if `1' =="AI"
replace `1' = "Antarctica" if `1' =="AQ"
replace `1' = "Antigua and Barbuda" if `1' =="AG"
replace `1' = "Argentina" if `1' =="AR"
replace `1' = "Armenia" if `1' =="AM"
replace `1' = "Aruba" if `1' =="AW"
replace `1' = "Australia" if `1' =="AU"
replace `1' = "Austria" if `1' =="AT"
replace `1' = "Azerbaijan" if `1' =="AZ"
replace `1' = "Bahamas (the)" if `1' =="BS"
replace `1' = "Bahrain" if `1' =="BH"
replace `1' = "Bangladesh" if `1' =="BD"
replace `1' = "Barbados" if `1' =="BB"
replace `1' = "Belarus" if `1' =="BY"
replace `1' = "Belgium" if `1' =="BE"
replace `1' = "Belize" if `1' =="BZ"
replace `1' = "Benin" if `1' =="BJ"
replace `1' = "Bermuda" if `1' =="BM"
replace `1' = "Bhutan" if `1' =="BT"
replace `1' = "Bolivia (Plurinational State of)" if `1' =="BO"
replace `1' = "Bonaire, Sint Eustatius and Saba" if `1' =="BQ"
replace `1' = "Bosnia and Herzegovina" if `1' =="BA"
replace `1' = "Botswana" if `1' =="BW"
replace `1' = "Bouvet Island" if `1' =="BV"
replace `1' = "Brazil" if `1' =="BR"
replace `1' = "British Indian Ocean Territory (the)" if `1' =="IO"
replace `1' = "Brunei Darussalam" if `1' =="BN"
replace `1' = "Bulgaria" if `1' =="BG"
replace `1' = "Burkina Faso" if `1' =="BF"
replace `1' = "Burundi" if `1' =="BI"
replace `1' = "Cabo Verde" if `1' =="CV"
replace `1' = "Cambodia" if `1' =="KH"
replace `1' = "Cameroon" if `1' =="CM"
replace `1' = "Canada" if `1' =="CA"
replace `1' = "Cayman Islands (the)" if `1' =="KY"
replace `1' = "Central African Republic (the)" if `1' =="CF"
replace `1' = "Chad" if `1' =="TD"
replace `1' = "Chile" if `1' =="CL"
replace `1' = "China" if `1' =="CN"
replace `1' = "Christmas Island" if `1' =="CX"
replace `1' = "Cocos (Keeling) Islands (the)" if `1' =="CC"
replace `1' = "Colombia" if `1' =="CO"
replace `1' = "Comoros (the)" if `1' =="KM"
replace `1' = "Congo (the Democratic Republic of the)" if `1' =="CD"
replace `1' = "Congo (the)" if `1' =="CG"
replace `1' = "Cook Islands (the)" if `1' =="CK"
replace `1' = "Costa Rica" if `1' =="CR"
replace `1' = "Croatia" if `1' =="HR"
replace `1' = "Cuba" if `1' =="CU"
replace `1' = "Curaçao" if `1' =="CW"
replace `1' = "Cyprus" if `1' =="CY"
replace `1' = "Czechia" if `1' =="CZ"
replace `1' = "Côte d'Ivoire" if `1' =="CI"
replace `1' = "Denmark" if `1' =="DK"
replace `1' = "Djibouti" if `1' =="DJ"
replace `1' = "Dominica" if `1' =="DM"
replace `1' = "Dominican Republic (the)" if `1' =="DO"
replace `1' = "Ecuador" if `1' =="EC"
replace `1' = "Egypt" if `1' =="EG"
replace `1' = "El Salvador" if `1' =="SV"
replace `1' = "Equatorial Guinea" if `1' =="GQ"
replace `1' = "Eritrea" if `1' =="ER"
replace `1' = "Estonia" if `1' =="EE"
replace `1' = "Eswatini" if `1' =="SZ"
replace `1' = "Ethiopia" if `1' =="ET"
replace `1' = "Falkland Islands (the) [Malvinas]" if `1' =="FK"
replace `1' = "Faroe Islands (the)" if `1' =="FO"
replace `1' = "Fiji" if `1' =="FJ"
replace `1' = "Finland" if `1' =="FI"
replace `1' = "France" if `1' =="FR"
replace `1' = "French Guiana" if `1' =="GF"
replace `1' = "French Polynesia" if `1' =="PF"
replace `1' = "French Southern Territories (the)" if `1' =="TF"
replace `1' = "Gabon" if `1' =="GA"
replace `1' = "Gambia (the)" if `1' =="GM"
replace `1' = "Georgia" if `1' =="GE"
replace `1' = "Germany" if `1' =="DE"
replace `1' = "Ghana" if `1' =="GH"
replace `1' = "Gibraltar" if `1' =="GI"
replace `1' = "Greece" if `1' =="GR"
replace `1' = "Greenland" if `1' =="GL"
replace `1' = "Grenada" if `1' =="GD"
replace `1' = "Guadeloupe" if `1' =="GP"
replace `1' = "Guam" if `1' =="GU"
replace `1' = "Guatemala" if `1' =="GT"
replace `1' = "Guernsey" if `1' =="GG"
replace `1' = "Guinea" if `1' =="GN"
replace `1' = "Guinea-Bissau" if `1' =="GW"
replace `1' = "Guyana" if `1' =="GY"
replace `1' = "Haiti" if `1' =="HT"
replace `1' = "Heard Island and McDonald Islands" if `1' =="HM"
replace `1' = "Holy See (the)" if `1' =="VA"
replace `1' = "Honduras" if `1' =="HN"
replace `1' = "Hong Kong" if `1' =="HK"
replace `1' = "Hungary" if `1' =="HU"
replace `1' = "Iceland" if `1' =="IS"
replace `1' = "India" if `1' =="IN"
replace `1' = "Indonesia" if `1' =="ID"
replace `1' = "Iran (Islamic Republic of)" if `1' =="IR"
replace `1' = "Iraq" if `1' =="IQ"
replace `1' = "Ireland" if `1' =="IE"
replace `1' = "Isle of Man" if `1' =="IM"
replace `1' = "Israel" if `1' =="IL"
replace `1' = "Italy" if `1' =="IT"
replace `1' = "Jamaica" if `1' =="JM"
replace `1' = "Japan" if `1' =="JP"
replace `1' = "Jersey" if `1' =="JE"
replace `1' = "Jordan" if `1' =="JO"
replace `1' = "Kazakhstan" if `1' =="KZ"
replace `1' = "Kenya" if `1' =="KE"
replace `1' = "Kiribati" if `1' =="KI"
replace `1' = "Korea (the Democratic People's Republic of)" if `1' =="KP"
replace `1' = "Korea (the Republic of)" if `1' =="KR"
replace `1' = "Kuwait" if `1' =="KW"
replace `1' = "Kyrgyzstan" if `1' =="KG"
replace `1' = "Lao People's Democratic Republic (the)" if `1' =="LA"
replace `1' = "Latvia" if `1' =="LV"
replace `1' = "Lebanon" if `1' =="LB"
replace `1' = "Lesotho" if `1' =="LS"
replace `1' = "Liberia" if `1' =="LR"
replace `1' = "Libya" if `1' =="LY"
replace `1' = "Liechtenstein" if `1' =="LI"
replace `1' = "Lithuania" if `1' =="LT"
replace `1' = "Luxembourg" if `1' =="LU"
replace `1' = "Macao" if `1' =="MO"
replace `1' = "Madagascar" if `1' =="MG"
replace `1' = "Malawi" if `1' =="MW"
replace `1' = "Malaysia" if `1' =="MY"
replace `1' = "Maldives" if `1' =="MV"
replace `1' = "Mali" if `1' =="ML"
replace `1' = "Malta" if `1' =="MT"
replace `1' = "Marshall Islands (the)" if `1' =="MH"
replace `1' = "Martinique" if `1' =="MQ"
replace `1' = "Mauritania" if `1' =="MR"
replace `1' = "Mauritius" if `1' =="MU"
replace `1' = "Mayotte" if `1' =="YT"
replace `1' = "Mexico" if `1' =="MX"
replace `1' = "Micronesia (Federated States of)" if `1' =="FM"
replace `1' = "Moldova (the Republic of)" if `1' =="MD"
replace `1' = "Monaco" if `1' =="MC"
replace `1' = "Mongolia" if `1' =="MN"
replace `1' = "Montenegro" if `1' =="ME"
replace `1' = "Montserrat" if `1' =="MS"
replace `1' = "Morocco" if `1' =="MA"
replace `1' = "Mozambique" if `1' =="MZ"
replace `1' = "Myanmar" if `1' =="MM"
replace `1' = "Namibia" if `1' =="NA"
replace `1' = "Nauru" if `1' =="NR"
replace `1' = "Nepal" if `1' =="NP"
replace `1' = "Netherlands (the)" if `1' =="NL"
replace `1' = "New Caledonia" if `1' =="NC"
replace `1' = "New Zealand" if `1' =="NZ"
replace `1' = "Nicaragua" if `1' =="NI"
replace `1' = "Niger (the)" if `1' =="NE"
replace `1' = "Nigeria" if `1' =="NG"
replace `1' = "Niue" if `1' =="NU"
replace `1' = "Norfolk Island" if `1' =="NF"
replace `1' = "Northern Mariana Islands (the)" if `1' =="MP"
replace `1' = "Norway" if `1' =="NO"
replace `1' = "Oman" if `1' =="OM"
replace `1' = "Pakistan" if `1' =="PK"
replace `1' = "Palau" if `1' =="PW"
replace `1' = "Palestine, State of" if `1' =="PS"
replace `1' = "Panama" if `1' =="PA"
replace `1' = "Papua New Guinea" if `1' =="PG"
replace `1' = "Paraguay" if `1' =="PY"
replace `1' = "Peru" if `1' =="PE"
replace `1' = "Philippines (the)" if `1' =="PH"
replace `1' = "Pitcairn" if `1' =="PN"
replace `1' = "Poland" if `1' =="PL"
replace `1' = "Portugal" if `1' =="PT"
replace `1' = "Puerto Rico" if `1' =="PR"
replace `1' = "Qatar" if `1' =="QA"
replace `1' = "Republic of North Macedonia" if `1' =="MK"
replace `1' = "Romania" if `1' =="RO"
replace `1' = "Russian Federation (the)" if `1' =="RU"
replace `1' = "Rwanda" if `1' =="RW"
replace `1' = "Réunion" if `1' =="RE"
replace `1' = "Saint Barthélemy" if `1' =="BL"
replace `1' = "Saint Helena, Ascension and Tristan da Cunha" if `1' =="SH"
replace `1' = "Saint Kitts and Nevis" if `1' =="KN"
replace `1' = "Saint Lucia" if `1' =="LC"
replace `1' = "Saint Martin (French part)" if `1' =="MF"
replace `1' = "Saint Pierre and Miquelon" if `1' =="PM"
replace `1' = "Saint Vincent and the Grenadines" if `1' =="VC"
replace `1' = "Samoa" if `1' =="WS"
replace `1' = "San Marino" if `1' =="SM"
replace `1' = "Sao Tome and Principe" if `1' =="ST"
replace `1' = "Saudi Arabia" if `1' =="SA"
replace `1' = "Senegal" if `1' =="SN"
replace `1' = "Serbia" if `1' =="RS"
replace `1' = "Seychelles" if `1' =="SC"
replace `1' = "Sierra Leone" if `1' =="SL"
replace `1' = "Singapore" if `1' =="SG"
replace `1' = "Sint Maarten (Dutch part)" if `1' =="SX"
replace `1' = "Slovakia" if `1' =="SK"
replace `1' = "Slovenia" if `1' =="SI"
replace `1' = "Solomon Islands" if `1' =="SB"
replace `1' = "Somalia" if `1' =="SO"
replace `1' = "South Africa" if `1' =="ZA"
replace `1' = "South Georgia and the South Sandwich Islands" if `1' =="GS"
replace `1' = "South Sudan" if `1' =="SS"
replace `1' = "Spain" if `1' =="ES"
replace `1' = "Sri Lanka" if `1' =="LK"
replace `1' = "Sudan (the)" if `1' =="SD"
replace `1' = "Suriname" if `1' =="SR"
replace `1' = "Svalbard and Jan Mayen" if `1' =="SJ"
replace `1' = "Sweden" if `1' =="SE"
replace `1' = "Switzerland" if `1' =="CH"
replace `1' = "Syrian Arab Republic" if `1' =="SY"
replace `1' = "Taiwan (Province of China)" if `1' =="TW"
replace `1' = "Tajikistan" if `1' =="TJ"
replace `1' = "Tanzania, United Republic of" if `1' =="TZ"
replace `1' = "Thailand" if `1' =="TH"
replace `1' = "Timor-Leste" if `1' =="TL"
replace `1' = "Togo" if `1' =="TG"
replace `1' = "Tokelau" if `1' =="TK"
replace `1' = "Tonga" if `1' =="TO"
replace `1' = "Trinidad and Tobago" if `1' =="TT"
replace `1' = "Tunisia" if `1' =="TN"
replace `1' = "Turkey" if `1' =="TR"
replace `1' = "Turkmenistan" if `1' =="TM"
replace `1' = "Turks and Caicos Islands (the)" if `1' =="TC"
replace `1' = "Tuvalu" if `1' =="TV"
replace `1' = "Uganda" if `1' =="UG"
replace `1' = "Ukraine" if `1' =="UA"
replace `1' = "United Arab Emirates (the)" if `1' =="AE"
replace `1' = "United Kingdom of Great Britain and Northern Ireland (the)" if `1' =="GB"
replace `1' = "United States Minor Outlying Islands (the)" if `1' =="UM"
replace `1' = "United States of America (the)" if `1' =="US"
replace `1' = "Uruguay" if `1' =="UY"
replace `1' = "Uzbekistan" if `1' =="UZ"
replace `1' = "Vanuatu" if `1' =="VU"
replace `1' = "Venezuela (Bolivarian Republic of)" if `1' =="VE"
replace `1' = "Viet Nam" if `1' =="VN"
replace `1' = "Virgin Islands (British)" if `1' =="VG"
replace `1' = "Virgin Islands (U.S.)" if `1' =="VI"
replace `1' = "Wallis and Futuna" if `1' =="WF"
replace `1' = "Western Sahara" if `1' =="EH"
replace `1' = "Yemen" if `1' =="YE"
replace `1' = "Zambia" if `1' =="ZM"
replace `1' = "Zimbabwe" if `1' =="ZW"
replace `1' = "Åland Islands" if `1' =="AX"
replace `1' = "Kosovo" if `1' =="XK"
replace `1' = "Congo, Democratic Republic of" if `1' =="ZR"

