local country "`0'"
********************************************************************************
/*This script is early stage script that uses the e-procurment product classification and translates to cpv sectors */
********************************************************************************

*Data
use "${utility_data}/country/`country'/starting_data/wb_mx_sesna_191125.dta", clear
********************************************************************************

// desc aw_item_class_id


gen product_str =  aw_item_class_id  //insert the string version of the unspsc code here
desc  product_str
replace product_str = strtrim(product_str)
replace product_str = stritrim(product_str)
replace product_str = strltrim(product_str)

gen cpv_div =""
replace cpv_div = "03" if regex(product_str,"^222")
replace cpv_div = "03" if regex(product_str,"^231")
replace cpv_div = "03" if regex(product_str,"^239")
replace cpv_div = "03" if regex(product_str,"^571")
replace cpv_div = "03" if regex(product_str,"^572")
replace cpv_div = "03" if regex(product_str,"^578")
replace cpv_div = "09" if regex(product_str,"^261")
replace cpv_div = "09" if regex(product_str,"^262")
replace cpv_div = "09" if regex(product_str,"^234")
replace cpv_div = "14" if regex(product_str,"^236")
replace cpv_div = "14" if regex(product_str,"^241")
replace cpv_div = "14" if regex(product_str,"^245")
replace cpv_div = "15" if regex(product_str,"^238")
replace cpv_div = "41" if regex(product_str,"^23800008")
replace cpv_div = "15" if regex(product_str,"^385")
replace cpv_div = "16" if regex(product_str,"^561")
replace cpv_div = "18" if regex(product_str,"^271")
replace cpv_div = "18" if regex(product_str,"^272")
replace cpv_div = "19" if regex(product_str,"^232")
replace cpv_div = "19" if regex(product_str,"^237")
replace cpv_div = "19" if regex(product_str,"^256")
replace cpv_div = "22" if regex(product_str,"^213")
replace cpv_div = "22" if regex(product_str,"^215")
replace cpv_div = "22" if regex(product_str,"^233")
replace cpv_div = "24" if regex(product_str,"^251")
replace cpv_div = "24" if regex(product_str,"^252")
replace cpv_div = "24" if regex(product_str,"^281")
replace cpv_div = "24" if regex(product_str,"^329")
replace cpv_div = "24" if regex(product_str,"^259")
replace cpv_div = "30" if regex(product_str,"^211")
replace cpv_div = "30" if regex(product_str,"^212")
replace cpv_div = "30" if regex(product_str,"^214")
replace cpv_div = "30" if regex(product_str,"^323")
replace cpv_div = "30" if regex(product_str,"^515")
replace cpv_div = "30" if regex(product_str,"^519")
replace cpv_div = "31" if regex(product_str,"^246")
replace cpv_div = "31" if regex(product_str,"^566")
replace cpv_div = "32" if regex(product_str,"^294")
replace cpv_div = "32" if regex(product_str,"^521")
replace cpv_div = "32" if regex(product_str,"^565")
replace cpv_div = "33" if regex(product_str,"^235")
replace cpv_div = "33" if regex(product_str,"^253")
replace cpv_div = "33" if regex(product_str,"^254")
replace cpv_div = "33" if regex(product_str,"^295")
replace cpv_div = "33" if regex(product_str,"^324")
replace cpv_div = "33" if regex(product_str,"^531")
replace cpv_div = "33" if regex(product_str,"^532")
replace cpv_div = "34" if regex(product_str,"^296")
replace cpv_div = "34" if regex(product_str,"^325")
replace cpv_div = "34" if regex(product_str,"^541")
replace cpv_div = "34" if regex(product_str,"^542")
replace cpv_div = "34" if regex(product_str,"^543")
replace cpv_div = "34" if regex(product_str,"^544")
replace cpv_div = "34" if regex(product_str,"^545")
replace cpv_div = "34" if regex(product_str,"^549")
replace cpv_div = "35" if regex(product_str,"^282")
replace cpv_div = "35" if regex(product_str,"^283")
replace cpv_div = "35" if regex(product_str,"^297")
replace cpv_div = "35" if regex(product_str,"^551")
replace cpv_div = "37" if regex(product_str,"^273")
replace cpv_div = "37" if regex(product_str,"^513")
replace cpv_div = "37" if regex(product_str,"^522")
replace cpv_div = "37" if regex(product_str,"^529")
replace cpv_div = "38" if regex(product_str,"^255")
replace cpv_div = "38" if regex(product_str,"^523")
replace cpv_div = "39" if regex(product_str,"^223")
replace cpv_div = "39" if regex(product_str,"^217")
replace cpv_div = "39" if regex(product_str,"^274")
replace cpv_div = "39" if regex(product_str,"^275")
replace cpv_div = "39" if regex(product_str,"^511")
replace cpv_div = "39" if regex(product_str,"^512")
replace cpv_div = "42" if regex(product_str,"^298")
replace cpv_div = "42" if regex(product_str,"^299")
replace cpv_div = "42" if regex(product_str,"^326")
replace cpv_div = "42" if regex(product_str,"^562")
replace cpv_div = "42" if regex(product_str,"^564")
replace cpv_div = "42" if regex(product_str,"^567")
replace cpv_div = "42" if regex(product_str,"^569")
replace cpv_div = "43" if regex(product_str,"^563")
replace cpv_div = "44" if regex(product_str,"^242")
replace cpv_div = "44" if regex(product_str,"^243")
replace cpv_div = "44" if regex(product_str,"^244")
replace cpv_div = "44" if regex(product_str,"^247")
replace cpv_div = "44" if regex(product_str,"^248")
replace cpv_div = "44" if regex(product_str,"^249")
replace cpv_div = "44" if regex(product_str,"^291")
replace cpv_div = "44" if regex(product_str,"^292")
replace cpv_div = "44" if regex(product_str,"^293")
replace cpv_div = "45" if regex(product_str,"^611")
replace cpv_div = "45" if regex(product_str,"^612")
replace cpv_div = "45" if regex(product_str,"^613")
replace cpv_div = "45" if regex(product_str,"^614")
replace cpv_div = "45" if regex(product_str,"^615")
replace cpv_div = "45" if regex(product_str,"^616")
replace cpv_div = "45" if regex(product_str,"^617")
replace cpv_div = "45" if regex(product_str,"^619")
replace cpv_div = "45" if regex(product_str,"^621")
replace cpv_div = "45" if regex(product_str,"^622")
replace cpv_div = "45" if regex(product_str,"^623")
replace cpv_div = "45" if regex(product_str,"^624")
replace cpv_div = "45" if regex(product_str,"^625")
replace cpv_div = "45" if regex(product_str,"^626")
replace cpv_div = "45" if regex(product_str,"^627")
replace cpv_div = "45" if regex(product_str,"^629")
replace cpv_div = "48" if regex(product_str,"^591")
replace cpv_div = "50" if regex(product_str,"^350")
replace cpv_div = "50" if regex(product_str,"^351")
replace cpv_div = "50" if regex(product_str,"^352")
replace cpv_div = "50" if regex(product_str,"^353")
replace cpv_div = "50" if regex(product_str,"^354")
replace cpv_div = "50" if regex(product_str,"^355")
replace cpv_div = "50" if regex(product_str,"^356")
replace cpv_div = "50" if regex(product_str,"^357")
replace cpv_div = "50" if regex(product_str,"^358")
replace cpv_div = "51" if regex(product_str,"^35301")
replace cpv_div = "60" if regex(product_str,"^34701")
replace cpv_div = "63" if regex(product_str,"^371")
replace cpv_div = "63" if regex(product_str,"^372")
replace cpv_div = "63" if regex(product_str,"^373")
replace cpv_div = "63" if regex(product_str,"^375")
replace cpv_div = "63" if regex(product_str,"^376")
replace cpv_div = "63" if regex(product_str,"^377")
replace cpv_div = "63" if regex(product_str,"^378")
replace cpv_div = "63" if regex(product_str,"^379")
replace cpv_div = "64" if regex(product_str,"^314")
replace cpv_div = "64" if regex(product_str,"^315")
replace cpv_div = "64" if regex(product_str,"^316")
replace cpv_div = "64" if regex(product_str,"^317")
replace cpv_div = "64" if regex(product_str,"^318")
replace cpv_div = "64" if regex(product_str,"^319")
replace cpv_div = "64" if regex(product_str,"^361")
replace cpv_div = "65" if regex(product_str,"^311")
replace cpv_div = "65" if regex(product_str,"^312")
replace cpv_div = "65" if regex(product_str,"^313")
replace cpv_div = "66" if regex(product_str,"^341")
replace cpv_div = "66" if regex(product_str,"^343")
replace cpv_div = "66" if regex(product_str,"^344")
replace cpv_div = "66" if regex(product_str,"^345")
replace cpv_div = "66" if regex(product_str,"^346")
replace cpv_div = "66" if regex(product_str,"^347")
replace cpv_div = "66" if regex(product_str,"^348")
replace cpv_div = "66" if regex(product_str,"^349")
replace cpv_div = "66" if regex(product_str,"^396")
replace cpv_div = "70" if regex(product_str,"^321")
replace cpv_div = "70" if regex(product_str,"^322")
replace cpv_div = "71" if regex(product_str,"^332")
replace cpv_div = "72" if regex(product_str,"^333")
replace cpv_div = "72" if regex(product_str,"^366")
replace cpv_div = "72" if regex(product_str,"^369")
replace cpv_div = "73" if regex(product_str,"^335")
replace cpv_div = "75" if regex(product_str,"^331")
replace cpv_div = "75" if regex(product_str,"^337")
replace cpv_div = "75" if regex(product_str,"^382")
replace cpv_div = "75" if regex(product_str,"^221")
replace cpv_div = "41" if regex(product_str,"^22100011")
replace cpv_div = "76" if regex(product_str,"^6170")
replace cpv_div = "79" if regex(product_str,"^327")
replace cpv_div = "79" if regex(product_str,"^336")
replace cpv_div = "79" if regex(product_str,"^338")
replace cpv_div = "79" if regex(product_str,"^339")
replace cpv_div = "79" if regex(product_str,"^362")
replace cpv_div = "79" if regex(product_str,"^363")
replace cpv_div = "79" if regex(product_str,"^364")
replace cpv_div = "79" if regex(product_str,"^384")
replace cpv_div = "79" if regex(product_str,"^383")
replace cpv_div = "79" if regex(product_str,"^381")
replace cpv_div = "80" if regex(product_str,"^334")
replace cpv_div = "90" if regex(product_str,"^216")
replace cpv_div = "92" if regex(product_str,"^365")
replace cpv_div = "92" if regex(product_str,"^359")
replace cpv_div = "98" if regex(product_str,"^358")
********************************************************************************
*Checks

*To check if all availble codes are matched to cpv
// count if missing(product_str)
// count if missing(cpv_div)
// br  product_str cpv_div if   !missing(product_str) & missing(cpv_div) & product_str!="."
*All good

// br  product_str cpv_div cpv_div_descr if !missing(product_str)
// tab cpv_div, m
drop product_str 
********************************************************************************

save "${country_folder}/`country'_wip.dta", replace
********************************************************************************
*END